### ISSUE TITLE
Establish data/minute usage quotas subject to Job Classification/GS/ES Scale

### ISSUE THREAD

**Issue by asrider01** [WhiteHouse/mobile-policy#1]
Use agency historical information on data and minute usage over the past five (5) years to establish the limits on the amount of data/minutes required for a specific job classification and/or GS/ES grade. This information is certainly available and can be used to set an outer bound control limit that ultimately caps the government's obligations.

**Comment by asrider01** [comment]
Hi Zach –

I’m just curious why this was closed. Is the period for comment over or is it something else?

Thanks,
Andy

**Comment by zachary-morgan** [comment]
@asrider01 That's correct. The public comment period has now been closed (see issue #18), and we closed all of the issues submitted before the deadline in order to officially count them as part of the public record. OMB will analyze all feedback submitted during the public comment period and revise the policy as necessary. Further discussion can continue in new threads if you'd like, but they will not count as part of the official record.
