### ISSUE TITLE
Why not consider all Government-wide Acquisition Contracts?

### ISSUE THREAD

**Issue by barkerw** [WhiteHouse/mobile-policy#5]
The NIH supports the efforts of OMB to improve the acquisition and management of common Information Technology (IT) and the goal of transitioning to Government-wide acquisition strategies that will also further accountability.  In particular, the NIH is operating under an executive agent designation from the Office of Management and Budget (OMB) to manage government-wide acquisition contracts (GWACs) for information technology (IT).  

One of these GWACs, Chief Information Officer-Commodities and Solutions (CIO-CS), offers to federal agencies the ability to quickly fulfill their requirements for IT commodities and commoditized solutions and includes wired and wireless networking tools (Category 6 – On-Premise Infrastructure) and Mobile Phone Voice Carrier Plans and Mobile Broadband Plans (Category 8 – Telecommunications Plans).  Additionally, the GWAC ordering system used for these GWACs is designed to capture data on government spend and have the data available to report to OMB as required.

Most recently, the NIH participated, along with NASA and GSA, in a Government-wide Strategic Solutions initiative for desktop and laptop configurations.  By OMB Memorandum for the Heads of Departments and Agencies, M-16-02 dated October 16, 2015, OMB mandated that civilian agencies leverage either the NIH CIO-CS GWAC, the NASA Solutions for Enterprise-Wide Procurement (SEWP), or the GSA IT Schedule 70 for laptop and desktop needs.  As stated in the memorandum, these contract vehicles were “generally awarded and are managed according the OMB’s category management principles.”

For mobile devices and services, the proposed memorandum encourages agencies to look at the government-wide GSA wireless solutions to consolidate their efforts for mobile solutions. Because the NIH and NASA GWACs were established promote Government-wide acquisition strategies that promote accountability and category management, the NIH recommends revising the subsection entitled “Consolidate Agency Requirements” under the section, “Transition to Government-wide Acquisition Strategies and Create Accountability” to include the NIH CIO-CS and NASA SWEP GWACs as sources to leverage their mobile consolidation efforts.  In the case of CIO-CS, contractors have invested in offering government-wide solutions that include mobile devices and plans and are available to assist government agencies in achieving these goals through the GWAC.

**Comment by waltbrown2** [comment]
Navy non-concurs with the below statement on Page 3 under “Consolidate Agency Requirements." 

Statement: "Therefore, effective immediately, except as provided in this policy, all covered agencies should not issue solicitations for new contract awards or exercise new option periods for mobile device and services, and should look to the existing government-wide GSA wireless solution to help in that consolidation effort."  

Navy recommends modifying this statement by replacing "and should look to the existing government-wide GSA wireless solution to help in that consolidation effort" with “and should look to a government-wide wireless solution to help in that consolidation effort.”  The reason being is DoD is in the process of awarding federal wide vehicles that have been approved by the OMB MAX process.  Stopping non-GSA procurements will jeopardize operational capabilities.  At time of order expiration under the current Navy solution the existing FSSI wireless solution will be expired.  Furthermore, this transition to the GSA vehicle is not cost effective for all Federal agencies.  DoD will experience an administrative fee of 1.5 percent levied by GSA without additional value.  Based on the current estimated DoD spend of $193 million annually this 1.5 percent will result in almost a $3 million fee paid to GSA on an annual basis just for the use of the overarching contract.  This $3 million fee paid to GSA does not include the administrative cost Navy will incur placing task orders for firm requirements against the overarching contract.  Navy is able to award and manage its own Federal-wide solution on an annual basis at a cost well below this $3 million dollar fee.  The follow-on Navy solution will be open for use by all Federal agencies, with no overarching fee to the user agencies.  Furthermore, the process established in the draft policy does not follow generally accepted Category Management principles because DoD ($193 million spend) has over seven times the amount of spend consolidated on its wireless solution than the GSA FSSI wireless solution with approximately $26 million.  It appears that it would be more efficient to have the non-DoD spend placed against the DoD Federal Solution.  It has also been DoD’s experience that as more spend flows to FSSI solutions the fee increases, yet there is no shared knowledge of what actual costs the fee is actually recovering.

**Comment by jonmjohnson** [comment]
The above non-concurrence by Mr. Brown is based on mistaken information.  Agencies do not pay fees to GSA for the use of the FSSI Wireless vehicle, therefore the above assessment is factually incorrect.
